// ─────────────────────────────────────────────────────────────────────────────
// firestoreSchema.js
//
// THIS FILE IS DOCUMENTATION ONLY — it is not imported anywhere.
// It describes the intended Firestore data model for Smart Study Planner,
// including fields, relationships, and how to extend the design for real
// multi-organization support in the future.
// ─────────────────────────────────────────────────────────────────────────────
//
//
// ── COLLECTION: organizations ────────────────────────────────────────────────
//
// Document ID: org_<uid>  (personal orgs — one per user)
//
// Fields:
//   name          string   Display name of the organization
//   createdAt     string   ISO-8601 timestamp
//   ownerId       string   Firebase Auth UID of the creator
//   memberUids    string[] List of UIDs who belong to this org
//                          (single-user orgs have just the owner)
//
// Notes:
//   - Currently every user has exactly one "personal org": org_<uid>
//   - When real multi-org support is added, create a real organization doc
//     and update users.organizationId to point to it
//   - Members are stored as a flat array here; for large orgs move them to
//     a sub-collection: organizations/<orgId>/members/<uid>
//
//
// ── COLLECTION: users ────────────────────────────────────────────────────────
//
// Document ID: <Firebase Auth UID>
//
// Fields:
//   email          string   User's email address
//   organizationId string   ID of the org this user currently belongs to
//                           (defaults to personalOrgId(uid) = "org_<uid>")
//   createdAt      string   ISO-8601 timestamp (set on first login/signup)
//
// Notes:
//   - Written (with merge: true) on every login so it is always up-to-date
//   - When multi-org support is added, organizationId will point to a real
//     organization document instead of the personal org placeholder
//
//
// ── COLLECTION: categories ───────────────────────────────────────────────────
//
// Document ID — two formats coexist until generateCategoryId() is updated:
//
//   Post-migration (existing docs renamed by migrate-to-readable-ids.mjs):
//     cat_<orgSlug>_<categorySlug>_<counter>
//     e.g. cat_org-abc123_work_1
//
//   Newly created docs (via generateCategoryId() in firestoreIds.js):
//     cat_<orgId>_<categorySlug>_<nanoid(10)>
//     e.g. cat_org_abc123_work_V3kD9pQrLm
//
//   NOTE: The audit script (audit-readable-ids.mjs) uses a counter-only regex
//   for categories, so new nanoid-suffix docs will appear as WARN(malformed)
//   until generateCategoryId() is updated to the counter format.  Track this
//   in follow-up task #149.
//
//   where orgSlug = slugify(orgId)  e.g. "org_abc123" → "org-abc123"
//
// Fields:
//   name           string   Normalized (UPPERCASED) category name
//   color          string   Hex color string, or "" for no color
//   displayOrder   number   Sort position in the sidebar
//   userId         string   Firebase Auth UID of the owner
//   organizationId string   Org this category belongs to (= "org_<uid>")
//   readableId     string   Copy of the document ID (for debugging/logging)
//
// Uniqueness guarantee:
//   nanoid(10) suffix provides ~1 quadrillion combinations; collisions are
//   essentially impossible across any number of users.
//
//
// ── COLLECTION: tasks ────────────────────────────────────────────────────────
//
// Document ID: task_<shortUserId>_<categorySlug>_<titleSlug>_<random4>
//   Generated by generateTaskId() in firestoreIds.js
//   where shortUserId  = first 6 characters of the Firebase Auth UID
//         categorySlug = slugify(category name)  e.g. "Math & Science" → "math-science"
//         titleSlug    = slugify(task title)      e.g. "Unity Notes"    → "unity-notes"
//         random4      = 4-character alphanumeric suffix from customAlphabet()
//
// Examples:
//   task_abc123_school_unity-notes_v3kD
//   task_xyz789_math_algebra-review_Q2pR
//
// Fields:
//   title          string   Task title
//   dueDate        string   "YYYY-MM-DD" — plain string, supports range filters
//   status         string   "PENDING" | "IN_PROGRESS" | "DONE"
//   description    string   Optional longer description
//   category       string   Matches a category name (UPPERCASED)
//   userId         string   Firebase Auth UID of the owner
//   organizationId string   Org this task belongs to (= "org_<uid>")
//   readableId     string   Copy of the document ID (for debugging/logging)
//   attachments    array    List of attachment objects (see below)
//
// Uniqueness guarantee:
//   A short user ID prefix combined with slugified category/title and a
//   4-character random alphanumeric suffix (via customAlphabet) makes
//   collisions effectively impossible.  See generateTaskId() in firestoreIds.js.
//
// Attachment object shape:
//   id             string   UUID
//   name           string   Original file name
//   displayName    string   User-editable display name
//   description    string   Optional description
//   url            string   Firebase Storage download URL
//   path           string   Storage path (used for deletion)
//   type           string   MIME type
//   size           number   File size in bytes
//   uploadedAt     string   ISO-8601 timestamp
//
// Notes:
//   - dueDate stored as a string so Firestore range queries work without
//     Timestamp conversion (string comparison "2025-04-19" < "2025-04-20" is safe)
//   - Currently queried by userId; to add org scoping later:
//       where("organizationId", "==", orgId)
//     alongside the existing where("userId", "==", uid) filter in taskService.js
//   - Composite indexes for userId + category + status + dueDate range are
//     defined in firestore.indexes.json
//
//
// ── QUERY SCOPING NOTES FOR MULTI-ORG ACTIVATION ─────────────────────────────
//
// When real multi-org support is turned on:
//
// 1. Replace personalOrgId(uid) calls with the user's real organization ID
//    (loaded from the users/<uid> document's organizationId field)
//
// 2. In taskService.js — add to both loadUserTasks and loadOverdueTasks:
//      where("organizationId", "==", orgId)
//    This ensures members of the same org see shared tasks if you allow it,
//    or keep the userId filter to keep tasks private per user within an org.
//
// 3. In loadCategories (App.jsx) — add:
//      where("organizationId", "==", orgId)
//    alongside the existing userId filter.
//
// 4. Update Firestore security rules to check organizationId membership
//    (e.g. the requesting user's UID must be in the org's memberUids array).
//
// 5. Deploy new composite indexes that include organizationId as a field.
//
//
// ── FIRESTORE SECURITY RULES — INTENDED ACCESS MODEL ─────────────────────────
//
// Rules live in firestore.rules (project root of the frontend package) and are
// deployed to Firebase via firebase.json.
//
// users/<uid>
//   read, write : request.auth.uid == uid
//   Rationale   : Each user may only read or write their own profile document.
//
// tasks/<taskId>
//   read, delete: resource.data.userId        == request.auth.uid
//              && resource.data.organizationId == 'org_' + request.auth.uid
//   create      : same checks on request.resource.data
//   update      : both existing and incoming data must satisfy the above
//   Rationale   : Double-check userId AND personal org so a user cannot read
//                 tasks owned by someone else in the same org (future-proofing).
//
// categories/<categoryId>
//   Same rule structure as tasks (userId + organizationId must match).
//
// organizations/<orgId>
//   read        : request.auth.uid in resource.data.memberUids
//   create      : ownerId == request.auth.uid && uid in memberUids
//   update/delete: resource.data.ownerId == request.auth.uid
//
// catch-all
//   All other paths: allow read, write: if false;
//
// ─────────────────────────────────────────────────────────────────────────────
