// ─────────────────────────────────────────────────────────────────────────────
// firestoreSchema.js
//
// THIS FILE IS DOCUMENTATION ONLY — it is not imported anywhere.
// It describes the Firestore data model for Smart Study Planner,
// including fields, relationships, and security model.
// ─────────────────────────────────────────────────────────────────────────────
//
//
// ── COLLECTION: organizations ────────────────────────────────────────────────
//
// Document ID: org_<schoolSlug>
//   Generated by schoolOrgId() in firestoreIds.js
//   e.g. "org_york-school", "org_springfield-high-school"
//
// Fields:
//   id              string    Mirrors the document ID
//   readableId      string    Same as document ID (for debugging)
//   name            string    Human-readable school/org name
//   createdBy       string    Full Firebase Auth UID of the creator
//   createdByEmail  string    Email address of the creator (for debugging)
//   source          string    Always "create_org_form"
//   schemaVersion   number    Always 2
//   createdAt       Timestamp Firestore server timestamp — set once at creation
//   updatedAt       Timestamp Firestore server timestamp — refreshed on changes
//
// Notes:
//   - Created by the admin when they submit the Create School Organization form.
//   - memberIds / memberEmails / ownerId / pendingInviteEmails are NOT used.
//     Membership is tracked exclusively in the memberships collection.
//   - Security rule for read: the current user must have a membership doc
//     at memberships/membership_<uid>_<orgId>.
//   - Security rule for create: createdBy == request.auth.uid,
//     schemaVersion == 2, source == "create_org_form".
//   - Security rule for update/delete: caller must be an active admin
//     (checked via their membership doc).
//
//
// ── COLLECTION: memberships ──────────────────────────────────────────────────
//
// Document ID: membership_<userId>_<organizationId>
//   Deterministic and predictable — used by Firestore security rules to check
//   admin status without a collection query.
//   e.g. "membership_UID123abc_org_york-school"
//
// Fields:
//   organizationId   string    ID of the organization
//   organizationName string    Human-readable org name
//   schoolSlug       string    Slug derived from organizationId (e.g. "york_school")
//   userId           string    Full Firebase Auth UID of the member
//   email            string    Member's email address
//   displayName      string|null  Member's display name
//   role             string    "admin" | "teacher" | "student"
//   status           string    Always "active"
//   source           string    "create_org_form" | "invitation"
//   schemaVersion    number    Always 2
//   readableId       string    Human-readable debug ID:
//                              mbr_<schoolSlug>_<role>_<emailSlug>
//                              e.g. "mbr_york_school_admin_kavolisarina_gmail_com"
//   createdAt        Timestamp Firestore server timestamp
//   updatedAt        Timestamp Firestore server timestamp
//   invitedBy        string    (invitation only) UID of the inviting admin
//   invitationId     string    (invitation only) Invitation document ID
//
// Admin check pattern used in security rules:
//   get(/databases/$(database)/documents/memberships/membership_$(uid)_$(orgId))
//     .data.role == "admin"
//
//
// ── COLLECTION: invitations ──────────────────────────────────────────────────
//
// Document ID: invite_<shortOrgId>_<emailSlug>_<random4>
//   Generated by generateInviteId() in firestoreIds.js
//
// Fields:
//   readableId        string    Mirrors the document ID
//   organizationId    string    Org the user is being invited to
//   organizationName  string    Human-readable org name
//   invitedEmail      string    Lowercase email of the invited user
//   invitedByUserId   string    UID of the admin who sent the invitation
//   invitedByEmail    string    Email of the admin
//   role              string    "teacher" | "student"
//   status            string    "pending" | "accepted" | "declined"
//   createdAt         Timestamp Server timestamp
//   acceptedAt        Timestamp|null
//   declinedAt        Timestamp|null
//   expiresAt         Timestamp|null
//
// Notes:
//   - Only active admins (checked via membership doc) can create invitations.
//   - Acceptance/decline is permitted only if request.auth.token.email
//     matches invitedEmail.
//   - The membership doc references invitationId for auditability.
//
//
// ── COLLECTION: users ────────────────────────────────────────────────────────
//
// Document ID: <Firebase Auth UID>  (full UID)
//
// Fields:
//   uid             string    Full Firebase Auth UID (mirrors document ID)
//   email           string    User's email address
//   displayName     string|null  Display name from Firebase Auth
//   organizationId  string    Active org ID (e.g. "org_york-school")
//   createdAt       Timestamp Set once at first login
//   updatedAt       Timestamp Refreshed on every login and org change
//
//
// ── COLLECTION: categories ───────────────────────────────────────────────────
//
// Document ID: cat_<shortUserId>_<categorySlug>_<random4>
//   Generated by generateCategoryId() in firestoreIds.js
//   e.g. "cat_AvU4Op_math-science_3kd9"
//
// Fields:
//   name             string   Normalized (UPPERCASED) category name
//   color            string   Hex color string, or "" for no color
//   displayOrder     number   Sort position in the sidebar
//   userId           string   Full Firebase Auth UID of the owner
//   userEmail        string   Email address of the owner
//   organizationId   string   Org this category belongs to
//   organizationName string   Human-readable name of the org
//   readableId       string   Copy of the document ID
//
//
// ── COLLECTION: tasks ────────────────────────────────────────────────────────
//
// Document ID: task_<shortUserId>_<categorySlug>_<titleSlug>_<random4>
//   Generated by generateTaskId() in firestoreIds.js
//   e.g. "task_AvU4Op_school_unity-notes_v3kD"
//
// Fields:
//   title          string   Task title
//   dueDate        string   "YYYY-MM-DD"
//   status         string   "PENDING" | "IN_PROGRESS" | "DONE"
//   description    string   Optional longer description
//   category       string   Matches a category name (UPPERCASED)
//   userId         string   Full Firebase Auth UID of the owner
//   organizationId string   Org this task belongs to
//   readableId     string   Copy of the document ID
//   attachments    array    List of attachment objects
//
//
// ── FIRESTORE SECURITY RULES — ACCESS MODEL ──────────────────────────────────
//
// users/<uid>
//   read, write : request.auth.uid == uid
//
// organizations/<orgId>
//   read   : exists(memberships/membership_<uid>_<orgId>)
//   create : createdBy == uid && schemaVersion == 2 && source == "create_org_form"
//   update : isAdmin(orgId)  — via get(memberships/membership_<uid>_<orgId>).role
//   delete : isAdmin(orgId)
//
// memberships/membership_<uid>_<orgId>
//   read   : resource.data.userId == uid
//   create : uid == data.userId
//            && membershipId == "membership_" + uid + "_" + orgId
//            && status == "active" && schemaVersion == 2
//            && (org creator admin path || invitation path)
//   update : uid == data.userId
//   delete : false
//
// invitations/<inviteId>
//   read   : uid == invitedByUserId || email == invitedEmail
//   create : uid == invitedByUserId && isAdmin(organizationId)
//   update : email == invitedEmail  (accept / decline)
//   delete : false
//
// tasks/<taskId>   and   categories/<categoryId>
//   read, write : resource.data.userId == uid
//
// ─────────────────────────────────────────────────────────────────────────────
