// ─────────────────────────────────────────────────────────────────────────────
// firestoreSchema.js
//
// THIS FILE IS DOCUMENTATION ONLY — it is not imported anywhere.
// It describes the Firestore data model for Smart Study Planner,
// including fields, relationships, and multi-organization design.
// ─────────────────────────────────────────────────────────────────────────────
//
//
// ── COLLECTION: organizations ────────────────────────────────────────────────
//
// Document ID: org_<shortUserId>_default
//   where shortUserId = first 6 characters of the Firebase Auth UID
//   e.g. "org_AvU4Op_default"
//
// Fields:
//   id            string   Mirrors the document ID
//   name          string   "<user email>'s Workspace"
//   ownerId       string   Full Firebase Auth UID of the creator
//   ownerEmail    string   Email address of the creator (for debugging/display)
//   memberIds     string[] Full UIDs of all org members — used by Firestore rules
//                          (single-user orgs contain only the owner)
//   memberEmails  string[] Email addresses of all members — parallel to memberIds
//                          Kept in sync: memberEmails[i] matches memberIds[i]
//                          For human-readable debugging only; not used in rules
//   createdAt     Timestamp Firestore server timestamp — set once at creation
//   updatedAt     Timestamp Firestore server timestamp — refreshed on changes
//
// Notes:
//   - Created exactly once per user, on their very first login/signup.
//   - If the users/<uid> document already has an organizationId the org is
//     NOT recreated. Only a missing organizationId triggers creation.
//   - Firestore security rules use memberIds (UIDs) exclusively.
//   - memberEmails is for debugging and display only — never trust it for auth.
//   - Members are stored as flat arrays; for large orgs consider moving them
//     to a sub-collection: organizations/<orgId>/members/<uid>
//
//
// ── COLLECTION: users ────────────────────────────────────────────────────────
//
// Document ID: <Firebase Auth UID>  (full UID, never the short user ID)
//
// Fields:
//   uid             string    Full Firebase Auth UID (mirrors the document ID)
//   email           string    User's email address
//   displayName     string|null  Display name from Firebase Auth (null if not set)
//   organizationId  string    ID of the org this user currently belongs to
//                             e.g. "org_AvU4Op_default"
//   createdAt       Timestamp Firestore server timestamp — set once at first login
//   updatedAt       Timestamp Firestore server timestamp — refreshed on every login
//
// Notes:
//   - Written in full on first login (when organizationId is not yet set).
//   - On subsequent logins only uid, email, displayName, and updatedAt are
//     refreshed (merge: true), preserving organizationId and createdAt.
//   - organizationId is the source of truth used by the app for scoping
//     tasks and categories — it is loaded from Firestore, not computed.
//   - When a user joins an existing org, update organizationId to the new
//     org's ID and add the user's UID to that org's memberIds array.
//
//
// ── COLLECTION: categories ───────────────────────────────────────────────────
//
// Document ID: cat_<orgId>_<slug>_<nanoid(10)>
//   Generated by generateCategoryId() in firestoreIds.js
//   e.g. "cat_org_AvU4Op_default_math-science_V3kD9pQrLm"
//
// Fields:
//   name           string   Normalized (UPPERCASED) category name
//   color          string   Hex color string, or "" for no color
//   displayOrder   number   Sort position in the sidebar
//   userId         string   Full Firebase Auth UID of the owner
//   organizationId string   Org this category belongs to
//   readableId     string   Copy of the document ID (for debugging/logging)
//
//
// ── COLLECTION: tasks ────────────────────────────────────────────────────────
//
// Document ID: task_<shortUserId>_<categorySlug>_<titleSlug>_<random4>
//   Generated by generateTaskId() in firestoreIds.js
//   e.g. "task_AvU4Op_school_unity-notes_v3kD"
//
// Fields:
//   title          string   Task title
//   dueDate        string   "YYYY-MM-DD" — plain string, supports range filters
//   status         string   "PENDING" | "IN_PROGRESS" | "DONE"
//   description    string   Optional longer description
//   category       string   Matches a category name (UPPERCASED)
//   userId         string   Full Firebase Auth UID of the owner
//   organizationId string   Org this task belongs to
//   readableId     string   Copy of the document ID (for debugging/logging)
//   attachments    array    List of attachment objects (see below)
//
// Attachment object shape:
//   id             string   UUID
//   name           string   Original file name
//   displayName    string   User-editable display name
//   description    string   Optional description
//   url            string   Firebase Storage download URL
//   path           string   Storage path (used for deletion)
//   type           string   MIME type
//   size           number   File size in bytes
//   uploadedAt     string   ISO-8601 timestamp
//
//
// ── MULTI-ORG FLOW ───────────────────────────────────────────────────────────
//
// On sign-up or first login (onAuthStateChanged in App.jsx):
//   1. Read users/<uid> — check for an existing organizationId.
//   2. If organizationId is missing (new user):
//      a. Generate resolvedOrgId = personalOrgId(uid)
//              = "org_" + uid.slice(0, 6) + "_default"
//      b. Create organizations/<resolvedOrgId> with id, name, ownerId,
//         memberIds: [uid], createdAt, updatedAt (all server timestamps).
//      c. Write users/<uid> with uid, email, displayName, organizationId,
//         createdAt, updatedAt (all server timestamps).
//   3. If organizationId already exists (returning user):
//      a. Use the stored value (no new org is created).
//      b. Merge-update uid, email, displayName, updatedAt only.
//   4. Store resolvedOrgId in React state (organizationId).
//      All subsequent task and category writes use this value.
//
// When a user joins an existing organization:
//   1. Add the user's UID to organizations/<orgId>.memberIds (arrayUnion).
//   2. Add the user's email to organizations/<orgId>.memberEmails (arrayUnion).
//   3. Update users/<uid>.organizationId to the existing orgId.
//   4. Do NOT create a new org document.
//
//
// ── FIRESTORE SECURITY RULES — ACCESS MODEL ──────────────────────────────────
//
// users/<uid>
//   read, write : request.auth.uid == uid
//
// organizations/<orgId>
//   read   : request.auth.uid in resource.data.memberIds
//   create : ownerId == request.auth.uid && uid in memberIds
//   update : resource.data.ownerId == request.auth.uid
//   delete : false
//
// tasks/<taskId>
//   read        : resource.data.userId == request.auth.uid
//   create      : request.resource.data.userId == request.auth.uid
//   update/delete: existing and incoming userId == request.auth.uid
//
// categories/<categoryId>
//   Same rule structure as tasks.
//
// ─────────────────────────────────────────────────────────────────────────────
