spring.application.name=smart-study-planner

spring.datasource.url=jdbc:postgresql://localhost:5432/studyplanner
spring.datasource.username=USER
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false